### ISSUE TITLE
After cloned, the site can only show like the pic.

### ISSUE THREAD

**Issue by Elitack** [luminousrubyist/airspace-jekyll#4] opened 2017-01-25 13:00 UTC
![2017-01-25 20-59-22](https://cloud.githubusercontent.com/assets/17812876/22291406/3769ed5a-e341-11e6-8f63-7da68c01017e.png)

**Comment by luminousrubyist** [comment] 2017-01-25 15:42
It looks like the page site is failing to load external resources. The CSS stylesheets for the page aren't present, meaning that fonts and layouts aren't rendered, and the page looks like a word document.

I would suggest that you use your browser's inspect element tool to find the stylesheets (which are definitely not loading) to locate the `<link rel="stylesheet" />` tags. I've done so here in my browser (Google Chrome).

![screen shot 2017-01-25 at 10 22 14 am](https://cloud.githubusercontent.com/assets/3442998/22296737/22affcd6-e2e9-11e6-9e82-914531a241a7.png)

Checking out the `href=` attributes of these tags should give you some clue as to why the stylesheets aren't loading. If the value of this attribute differs from the actual location of the stylesheets served by Jekyll, the source of your issue should become clear.

I couldn't reproduce your issue by cloning the repository. However, if you have attempted to change the `baseurl` of your site in `_config.yml` to the root, make sure you set the value to `baseurl: ""` and not `baseurl: "/"`. I tried doing the latter and broke the site's stylesheets, producing the exact situation you described:

![screen shot 2017-01-25 at 10 38 44 am](https://cloud.githubusercontent.com/assets/3442998/22297170/8186cde2-e2ea-11e6-80df-c50ad4f088e1.png)

I am closing this issue because I could not reproduce the result you put forth. However, if my suggestions do not solve your difficulties, reopen the issue with screenshots of your website and its source code, and I'll do my best to help you!

Best,

LR

**Closed by luminousrubyist** 2017-01-25 15:42 UTC

**Comment by Elitack** [comment] 2017-02-01 14:08
Yes,  it's the problem about the ```baseurl```, thx for your suggestions!
